### ISSUE TITLE
Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by sizhky** [sksq96/pytorch-summary#16]
Hi,

I'm getting the following error while trying to print model summary. The model, however, is training without an issue (when not printing the summary)

```python
...
    print(summary(model, (3, 30, 16)))
...
```

```python
Traceback (most recent call last):
  File "slideCNN-train.py", line 57, in <module>
    print(summary(model, (3, 30, 16)))
  File "/home/yeshwanth/.local/lib/python2.7/site-packages/torchsummary/torchsummary.py", line 56, in summary
    model(x)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```

**Comment by sizhky** [comment]
I could fix it temporarily by using `model.to(device)`

```python
...
  print(summary(model.to(device), (3, 30, 16)))
...
```

**Comment by seongkyun** [comment]
I think the following code is better for the test.
`summary(model, (3, 30, 16), device=device_name)`
device_name should be the `str` type.
