### ISSUE TITLE
When running DenseNet and MobileNet I got the following errors

### ISSUE THREAD

**Issue by sriharsha0806** [sksq96/pytorch-summary#2]
MobileNet:
Traceback (most recent call last):
  File "MobileNet.py", line 365, in <module>
    summary(model, (3,32,32))
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 56, in summary
    model(x)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "MobileNet.py", line 114, in forward
    x = self.model(x)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 359, in __call__
    hook_result = hook(self, input, result)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 28, in hook
    params +=  th.prod(th.LongTensor(list(module.bias.size())))
AttributeError: 'NoneType' object has no attribute 'size'

DenseNet:
Traceback (most recent call last):
  File "DenseNet.py", line 237, in <module>
    summary(model, (3,32,32))
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 56, in summary
    model(x)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "DenseNet.py", line 226, in forward
    features = self.features(x)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 359, in __call__
    hook_result = hook(self, input, result)
  File "/home/sriharsha/miniconda3/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 28, in hook
    params +=  th.prod(th.LongTensor(list(module.bias.size())))
AttributeError: 'bool' object has no attribute 'size'

**Comment by sksq96** [comment]
- Yes, I verified the error for `DenseNet` and `MobileNet`.
- I found a bug, pertinent to bias in the code, which I'll fix. 
- Meanwhile could you share the implementation you used, to be sure the bugfix solves the issue.

**Comment by MKFMIKU** [comment]
Face same error too on DenseNet

**Comment by sksq96** [comment]
I have fixed the issue with these models. Please upgrade the package or pull the latest code to test the changes. 

I'm closing this issue, feel free to open it up if you face any further issues.

**Comment by Hrushikesh-github** [comment]
torchsummary is not working for densenet
```
>>> model2 = densenet121(pretrained=False)
>>> img = (3, 227, 227)
>>> summary(model2, img)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchvision/models/densenet.py", line 192, in forward
    features = self.features(x)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchvision/models/densenet.py", line 111, in forward
    new_features = layer(features)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 731, in _call_impl
    hook_result = hook(self, input, result)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 19, in hook
    summary[m_key]["input_shape"] = list(input[0].size())
AttributeError: 'list' object has no attribute 'size'
>>> img = (3, 224, 224)
>>> summary(model2, img)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchvision/models/densenet.py", line 192, in forward
    features = self.features(x)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchvision/models/densenet.py", line 111, in forward
    new_features = layer(features)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 731, in _call_impl
    hook_result = hook(self, input, result)
  File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 19, in hook
    summary[m_key]["input_shape"] = list(input[0].size())
AttributeError: 'list' object has no attribute 'size'

```

**Comment by swuxyj** [comment]
> torchsummary is not working for densenet
> 
> ```
> >>> model2 = densenet121(pretrained=False)
> >>> img = (3, 227, 227)
> >>> summary(model2, img)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 72, in summary
>     model(*x)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchvision/models/densenet.py", line 192, in forward
>     features = self.features(x)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
>     input = module(input)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchvision/models/densenet.py", line 111, in forward
>     new_features = layer(features)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 731, in _call_impl
>     hook_result = hook(self, input, result)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 19, in hook
>     summary[m_key]["input_shape"] = list(input[0].size())
> AttributeError: 'list' object has no attribute 'size'
> >>> img = (3, 224, 224)
> >>> summary(model2, img)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 72, in summary
>     model(*x)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchvision/models/densenet.py", line 192, in forward
>     features = self.features(x)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
>     input = module(input)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchvision/models/densenet.py", line 111, in forward
>     new_features = layer(features)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torch/nn/modules/module.py", line 731, in _call_impl
>     hook_result = hook(self, input, result)
>   File "/home/hrushikesh/.local/bin/.virtualenvs/adityaya/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 19, in hook
>     summary[m_key]["input_shape"] = list(input[0].size())
> AttributeError: 'list' object has no attribute 'size'
> ```

I also faced this problem until   `pip install torch-summary==1.4.4`
