### ISSUE TITLE
python2 import error in SyntaxError

### ISSUE THREAD

**Issue by QiaoranC** [sksq96/pytorch-summary#28]
using pip install
error when  `from torchsummary import summary`
```
>>> from torchsummary import summary
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qiaoran/python/python2/lib/python2.7/site-packages/torchsummary/__init__.py", line 1, in <module>
    from .torchsummary import summary
  File "/home/qiaoran/python/python2/lib/python2.7/site-packages/torchsummary/torchsummary.py", line 9
    def summary(model, *input_size, batch_size=-1, device="cuda"):
                                             ^
SyntaxError: invalid syntax
```

**Comment by sksq96** [comment]
The code is fixed to run correctly on Python2 now. Thanks.
