### ISSUE TITLE
Invalid syntax error caused by parameter *input_size in Python 2.7 .

### ISSUE THREAD

**Issue by davidleejy** [sksq96/pytorch-summary#35]
Hello,
Was really pleased to find this repo to help visualize my neural networks.  No errors encountered in python 3.6. However, I get the following error in python 2.7 .

Failing environment:
Ubuntu 16.04
python 2.7 (anaconda)
$ pip install torchsummary

Running the demo code provided by this repo gives:

Traceback:
``` python
Traceback (most recent call last):
  File "/home/dl/code/dljy-densepose/print_resnet.py", line 13, in <module>
    from torchsummary import summary
  File "/home/dl/anaconda3/envs/torch_py27/lib/python2.7/site-packages/torchsummary/__init__.py", line 1, in <module>
    from .torchsummary import summary
  File "/home/dl/anaconda3/envs/torch_py27/lib/python2.7/site-packages/torchsummary/torchsummary.py", line 9
    def summary(model, *input_size, batch_size=-1, device="cuda"):
                                             ^
SyntaxError: invalid syntax
```

A remedy:
``` python
# Remove astericks from *input_size in function signature:
def summary(model, input_size, batch_size=-1, device="cuda"):

     ... omitted code ...

     #model(*x)   # change this also.
     x = torch.rand(input_size)
     model(x)
```

**Comment by sksq96** [comment]
Thank you for the suggestions.  The code runs correctly on Python2 now.
