### ISSUE TITLE
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by forhonourlx** [sksq96/pytorch-summary#52]
Traceback (most recent call last):
  File "examples.py", line 566, in <module>
    ppo_pixel_atari(game)
  File "examples.py", line 391, in ppo_pixel_atari
    run_steps(PPOAgent(config))
  File "/home/simon/Desktop/DeepRL.old/deep_rl/agent/PPO_agent.py", line 25, in __init__
    torchsummary.summary(self.network,(4, 84, 84))
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 72, in summary
    model(*x)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/simon/Desktop/DeepRL.old/deep_rl/network/network_heads.py", line 173, in forward
    phi = self.network.phi_body(obs)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/simon/Desktop/DeepRL.old/deep_rl/network/network_bodies.py", line 19, in forward
    y = F.relu(self.conv1(x))
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by MohanZhou** [comment]
There are two ways to fix it:
1. convert your network to cuda
2. call `torchsummary.summary` with `device='cpu'`

**Comment by gceboh** [comment]
https://github.com/sksq96/pytorch-summary/issues/36
