### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'apply'

### ISSUE THREAD

**Issue by mrgloom** [sksq96/pytorch-summary#75]
Model:
https://www.adrianbulat.com/downloads/python-fan/depth-2a464da4ea.pth.tar

```
Traceback (most recent call last):
  File "print_model_summary.py", line 6, in <module>
    summary(model, input_size=(3,128,128))
  File "/usr/local/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 68, in summary
    model.apply(register_hook)
AttributeError: 'dict' object has no attribute 'apply'
```

```
import torch
from torchsummary import summary

model = torch.load('depth-2a464da4ea.pth.tar', map_location='cpu')
summary(model, input_size=(3,128,128))
```

**Comment by mrgloom** [comment]
```
import torch
from torchsummary import summary

model = torch.load('pretrained_models/latest_net_DA.pth', map_location='cpu')
summary(model, (3, 128, 128))
```

```
Traceback (most recent call last):
  File "print_model_summary.py", line 8, in <module>
    summary(model, (3, 128, 128))
  File "/usr/local/lib/python3.6/site-packages/torchsummary/torchsummary.py", line 68, in summary
    model.apply(register_hook)
AttributeError: 'collections.OrderedDict' object has no attribute 'apply'
```

Models from:
https://drive.google.com/drive/folders/1jvD8R-Ggo3Seg2tF-JsqlOjwropVwN1S

Seems like it's `.pth` only containing weights.
https://stackoverflow.com/questions/49941426/attributeerror-collections-ordereddict-object-has-no-attribute-eval

**Comment by ak9250** [comment]
@mrgloom also got this error were you able to resolve it?

**Comment by skim2257** [comment]
bump
Looking for a solution as well.

**Comment by chamboin** [comment]
Is there any solution?

**Comment by nguyenvulong** [comment]
bump

**Comment by VeeranjaneyuluToka** [comment]
Anybody has solution for this problem, i am also facing same issue.
